// generated by 05_tools/aob_sigs.py from the game exe; do not edit
#pragma once
#include <cstdint>
namespace ki {
static const char* KNOWN_EXE_SHA256 = "33bbd291e1a4e280fc07f614fc6a10039c1de7cd2dea33153b0e9c315c31edf6";
struct Sig { const char* name; uint32_t rva; const char* pattern; };
static const Sig SIGS[] = {
  {"dispatcher", 0x5dfe50, "48 89 5c 24 08 48 89 74 24 10 48 89 7c 24 20 55 41 56 41 57 48 8d 6c 24 b9 48 81 ec ?? ?? ?? ?? 45 8b f9 4d 8b f0 49 8b 50 20 41 8b 40 18 c1 e8 06"},
  {"rootInvoke", 0x1122ef0, "40 53 55 56 57 41 54 41 55 41 56 41 57 48 81 ec ?? ?? ?? ?? 48 8b 05 ?? ?? ?? ?? 48 33 c4 48 89 84 24 c0 02 00 00"},
  {"objInvoke", 0x1150a00, "40 55 53 56 57 41 54 41 55 41 56 41 57 48 8d 6c 24 b8 48 81 ec ?? ?? ?? ?? 48 8b 05 ?? ?? ?? ?? 48 33 c4 48 89 45 38 49 8b f8 4c 89 44 24 70 4c 8b e2"},
  {"objGetMember", 0x11502e0, "40 55 53 56 57 41 54 41 56 41 57 48 8d 6c 24 e1 48 81 ec ?? ?? ?? ?? 48 8b 05 ?? ?? ?? ?? 48 33 c4 48 89 45 17 49 8b d9 4d 8b f8 48 8b f2 48 8b 41 08"},
  {"valueRelease", 0x350bd0, "40 53 48 83 ec 20 48 8b d9 8b 41 18 c1 e8 06 a8 01 74 ?? 48 8b 49 10 48 8b 01"},
  {"advance", 0xe4a700, "48 8b c4 48 89 58 10 48 89 70 18 48 89 78 20 55 41 54 41 55 41 56 41 57 48 8d 68 c8 48 81 ec ?? ?? ?? ?? 0f 29 70 c8 0f 29 78 b8 44 0f 29 40 a8 44 0f 29 48 98 48 8b 05 ?? ?? ?? ?? 48 33 c4 48 89 45 c0"},
  {"matchState", 0x9d7240, "48 8b 05 ?? ?? ?? ?? 48 85 c0 74 ?? f7 40 48 ?? ?? ?? ?? 75 ?? 33 c0 c3 cc cc cc cc cc cc cc cc 48 89 5c 24 18 48 89 4c 24 08 55 56 57 41 54 41 55 41 56 41 57 48 83 ec 30 4c 8b f1 e8 ?? ?? ?? ??"},
  {"levelState", 0x68b020, "48 8b 05 ?? ?? ?? ?? 8b 80 fc 0b 00 00 c3 cc cc 48 8b 05 ?? ?? ?? ?? 48 63 d1 f3 0f 10 84 90 c0 10 00 00 c3"},
  {"roundState", 0x74d520,"48 8b 05 ?? ?? ?? ?? 48 85 c0 74 ?? f7 40 48 ?? ?? ?? ?? 75 ?? 33 c0 c3 cc cc cc cc cc cc cc cc 89 54 24 10 48 83 ec 28 4c 8b 09 44 8b c2 4c 8b 51 08"},
};
}
