// Localization table: hash -> text (kiaccess\data\strings_en.tsv, generated by 05_tools/strings_decode.py);
// keys hash as CRC32(lowercase key); "&literal" and "#<decimal crc32>" (possibly signed) are resolved too.
#pragma once
#include "common.h"
#include <unordered_map>

namespace ki {

class Strings {
public:
    bool load(const std::wstring& tsvPath);
    size_t size() const { return byHash_.size(); }
    std::string resolve(const json& key) const;          // Python: self.S.resolve(key); None -> ""
    std::string resolve(const std::string& key) const;
    static uint32_t crc32(const std::string& s);
private:
    std::unordered_map<uint32_t, std::string> byHash_;
};

}  // namespace ki
